# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Le Club
#email: hello[at]leclub.lv
description: >
   Disrupting beauty shopping. Powered by AI. And You.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leclub.me" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Le Club'
bio: >
 Disrupting beauty shopping. Powered by AI. And You.
author_image: "/assets/images/author.jpg"
#twitter_username: jekyllrb
#github_username:  jekyll

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
